{
  // general
  "subject": "Document <{{document}}> Task failed",
  "body": "Document Name: {{documentName}};\r\nDocument type: {{documentType}};\r\nExecution Time: {{executionTime}}\r\nError Message: {{errorMessage}}\r\n",

  // documentTypeName
  "dbd!name": "Dashboards",
  "rdl!name": "Reports",
  "dataset!name": "Datasets",
  "dsc!name": "Data Sources",
  "smdsc!name": "Data Models",

  // executionException Common
  "executionErr_10001": "[Execution Error] Unknown cot task status.",
  "executionErr_10002": "[Execution Error] Cot task not found.",
  "executionErr_10003": "[Execution Error] Cot task not created.",
  "executionErr_10004": "[Execution Error] An IO error occurred: {{errorMessage}}.",

  // executionException DataSourceTask
  "executionErr_11001": "[Execution Error] The specified directory is not found or permission deny.",
  "executionErr_11002": "[Execution Error] You don\"t have permission to access datasource.",
  "executionErr_11003": "[Execution Error] File:{{errorUsing}} is being used and file:{{errorDestroy}} can\\'t be extracted,please check the file format.",
  "executionErr_11004": "[Execution Error] File:{{errorUsing}} is being used.",
  "executionErr_11005": "[Execution Error] File:{{errorDestroy}} can\\'t be extracted, please check the file format or the file password.",
  "executionErr_11006": "[Execution Error] Overwrite operation does not support multiple files.",
  "executionErr_11007": "[Execution Error] Cannot get correct response from refresh cot api.",

  // executionException DatasetRefresh
  "executionErr_12001": "[Execution Error] RefreshCot exception: {{errorMessage}}.",

  "executionErr_17002": "[Execution Error] Access denied to the dataset.",
  "executionErr_17005": "[Execution Error] No available COT worker threads.",
  "executionErr_17006": "[Execution Error] Dataset task manager reported an error.  \r\n{{errorMessage}}",
  "executionErr_17111": "[Execution Error] CotWorker reported an error.  \r\n{{errorMessage}}",
  "executionErr_17200": "[Execution Error] Unexpected runtime error.  \r\n{{errorMessage}}",

  "executionErr_18002": "[Execution Error] [Organization:{{organization}}] Access denied to the dataset.",
  "executionErr_18005": "[Execution Error] [Organization:{{organization}}] No available COT worker threads.",
  "executionErr_18006": "[Execution Error] [Organization:{{organization}}] Dataset task manager reported an error.  \r\n{{errorMessage}}",
  "executionErr_18111": "[Execution Error] [Organization:{{organization}}] CotWorker reported an error.  \r\n{{errorMessage}}",
  "executionErr_18200": "[Execution Error] [Organization:{{organization}}] Unexpected runtime error.  \r\n{{errorMessage}}",

  // executionException DashboardExport
  "executionErr_13001": "[Execution Error] {{errorMessage}}.",
  "executionErr_13002": "[Execution Error] the \"Portal URI\" in \"UI Settings\" is empty.",
  "executionErr_13003": "[Execution Error] Invalid token, Please re-edit this task to get a valid token.",
  "executionErr_13004": "[Execution Error] Can't navigate to target dashboard, Please re-check the \"Portal URI\" in \"UI Settings\".",
  "executionErr_13005": "[Execution Error] Please enable PDF Export to execute this task.",
  "executionErr_13006": "[Execution Error] Please install a Chrome to continue.",
  "executionErr_13007": "[Execution Error] Failed to launch Chrome, make sure the Chrome is executable.",
  "executionErr_13008": "The task is canceled by administrator or the task is automatically canceled because the task has timed out or the task is aborted.",

  // refreshTokenException
  "securityErr_10001": "[Security Error] Discovery Client Retrieves discovery document error.",
  "securityErr_10002": "[Security Error] Get discovery document error.",
  "securityErr_10003": "[Security Error] Request refresh token error.",
  "securityErr_10004": "[Security Error] Get access token error: \n1, The organization in which the task is created does not exist.\n2, The user who creates the task is not in the specified organization.\n3, The user who creates the task does not exist.",

  // deploymentException
  "deploymentErr_10001": "[Deployment Error] Email domain error: Recipients email address outside your organization.",
  "deploymentErr_10002": "[Deployment Error] Mailing error: {{errorMessage}}.",
  "deploymentErr_10003": "[Deployment Error] Mailing error: {{errorMessage}}.",
  "deploymentErr_10004": "[Deployment Error] Mailing error: {{errorMessage}}.",
  "deploymentErr_10005": "[Deployment Error] File share error: {{errorMessage}}",
  "deploymentErr_10006": "[Deployment Error] Result expiration date have already passed.",
  "deploymentErr_10007": "[Deployment Error] Not delivered because the report is empty.",
  "deploymentErr_10008": "[Deployment Error] Access to the path \"{{filePath}}\" is denied.",
  "deploymentErr_10009": "[Deployment Error] Could not find a part of the path \"{{filePath}}\"."
}