export const portalES: LanguageKeyValueMap = {
	'CotManagement!title': 'Dataset Cache',
	'CotManagement!description': 'View Dataset Cache',
};

export const datasetES: LanguageKeyValueMap = {
	'OK': 'OK',
	'Cancel': 'Cancel',
	'cot-title': 'Name',
	'cot-creator': 'Created By',
	'cot-tenant': 'Organization',
	'cot-rowCount': 'Row Count',
	'cot-operation': 'Status',
	'cot-lastUpdated': 'Last Updated',
	'cot-lastErrorCode': 'Last Result',
	'cot-lastErrorData': 'Last Error Message',
	'succeed': 'Succeed',
	'failed': 'Failed',
	'Standby': 'Succeed',
	'Create': 'Creating',
	'Overwrite': 'Recreating',
	'AppendData': 'Incremental updating',
	'Failed': 'Failed',
	'onlyShowFailed': 'Only show failed dataset cache',
	'noCotTip': 'No matching dataset cache',
	'emptyCot': 'There is no dataset cache in the current system',
	'copy': 'Copy Error Message',

	'batchRefreshConfirmtitle': 'Batch refresh dataset',
	'batchRefreshMessage': 'Are you sure to batch refresh the dataset cache?',
	'batchRefreshCotCache': 'Refresh dataset cache',
	'invalidParameter': 'Invalid parameter',
	'refreshError': 'Refresh dataset cache error.',

	// update error
	err_100001: 'Invalid parameter: {{name}}.',
	err_100002: 'Internal server error: {{message}}.',
	err_100009: 'This document is being updated by another operation. Please try later.',
	err_100012: 'Invalid user context: {{claimName}}.',
	err_100014: 'You have not enough permission to access datasource "{{name}}"',
	err_100015: 'You have not enough permission to access referenced datasources, or one or more datasources do not exist.',
	err_100017: 'The "{{key}}" value "{{value}}" on "{{ptype}}" is an invalid {{dtype}} value.',
	err_100018: 'Document not found.',
	err_100019: 'You don not have permission to access the document.',
	err_100021: 'Can not connect to datasource {{name}}.',
	err_100022: 'You don\'t have permission to update the data set.',
	err_100023: 'No available COT worker.',
	err_100018_desc: 'Error trying to resolve datasource "{{ids}}"',
	err_400001: 'Refresh failed. Please check parameter "{{propertyName}}" with orgnization context. The organization of the current user does not have this context.',

	err_410511: 'Refresh failed: Failed to execute create/update/delete/copy sql (redirected to server) on remote analysis database.',
	err_410512: 'Refresh failed: Failed to calculate dataset due to runtime error.',
	err_410003: 'Refresh failed: Logical data type is not supported.',
	err_410005: 'Refresh failed: Invalid dataset calculation result.',
	err_410006: 'Refresh failed: Access denied to temp data file directory.',
	err_410014: 'Refresh failed: Failed to convert value to target data type. \nRow index: {{rowIndex}}, column index: {{columnIndex}}.',
	err_410102: 'Refresh failed: Unknown runtime errors occurred.',
	err_410105: 'Refresh failed: Failed to execute command on analysis database.',
	err_410125: 'Refresh failed: Internal error. The code line should not be reached.',
	err_410137: 'Refresh failed: Invalid analysis database info.',
	err_410138: 'Refresh failed: Failed to create entry for cached data.',
	err_410139: 'Refresh failed: Failed to append data to cached data.',
	err_410140: 'Refresh failed: Failed to write binary data to analysis database.',
	err_410141: 'Refresh failed: Failed to delete inserted rows.',

	err_DataSourceAccessDenied: 'You do not have permission to access datasource.',
	err_DataSourceNotFound: 'Specified datasource document is not found.',
	err_DataSourceIntegrityCheck: 'Data source integrity check error.',
	err_UserNotInOrgnization: 'Current user is not in any orgnization. Please check parameter with orgnization context.',
	err_3000: 'The calculation failed due to exceptions or the calculation was canceled by administrator.',

	gtClipboardError: 'Cannot write data to clipboard',
	gtClipboardSuccess: 'Successfully copied to clipboard',
};
